name : learning-github-actions
run-name : ${{github.actor}} is learning Github Actions

on : [push]
jobs : 
    Send-Message:
        runs-on: ubuntu-latest
        steps:
            - name: Send Start Message
              uses: appleboy/telegram-action@master
              with:
                to: ${{secrets.TELEGRAM_TARGET_USER_ID}}
                token: ${{secrets.TELEGRAM_BOT_TOKEN}}
                message: "The file has started compiling here ${{github.run_id}}"
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Compile Latex Document
              uses: xu-cheng/latex-action@v2
              with:
                working_directory: src
                root_file: resume.tex
                latexmk_use_lualatex: true
            - name: Upload our file
              uses: actions/upload-artifact@v4
              with:
                name: output
                path: output/src/resume.pdf
            - name: Upload our file to Telegram
              uses: appleboy/telegram-action@master
              with:
                to: ${{secrets.TELEGRAM_TARGET_USER_ID}}
                token: ${{secrets.TELEGRAM_BOT_TOKEN}}
                message: "Congratulations! Your file has been compiled !"
                document: src/main.pdf