name : learning-github-actions
run-name : ${{github.actor}} is learning Github Actions

on : [push]
jobs : 
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Compile Latex Document
              uses: xu-cheng/latex-action@v2
              with:
                working_directory: src
                root_file: main.tex
                latexmk_use_lualatex: true
            - name: Upload our file
              uses: actions/upload-artifact@v3
              with:
                name: file upload
                path: src/main.pdf
                if-no-file-found: error
